# -*- coding: utf-8 -*-

"""
postnlecommerceapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from apimatic_core.authentication.header_auth import HeaderAuth


class CustomHeaderAuthentication(HeaderAuth):

    @property
    def error_message(self):
        """Display error message on occurrence of authentication failure
        in CustomHeaderAuthentication

        """
        return "CustomHeaderAuthentication: apikey is undefined."

    def __init__(self, apikey):
        auth_params = {}
        if apikey:
            auth_params["apikey"] = apikey
        super().__init__(auth_params=auth_params)
        self._apikey = apikey
