# -*- coding: utf-8 -*-

"""
postnlecommerceapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from postnlecommerceapis.api_helper import APIHelper
import postnlecommerceapis.exceptions.api_exception
from postnlecommerceapis.models.error_7 import Error7


class LabellingResponseInvalidException(postnlecommerceapis.exceptions.api_exception.APIException):
    def __init__(self, reason, response):
        """Constructor for the LabellingResponseInvalidException class

        Args:
            reason (string): The reason (or error message) for the Exception
                to be raised.
            response (HttpResponse): The HttpResponse of the API call.

        """
        super(LabellingResponseInvalidException, self).__init__(reason, response)
        dictionary = APIHelper.json_deserialize(self.response.text)
        if isinstance(dictionary, dict):
            self.unbox(dictionary)

    def unbox(self, dictionary):
        """Populates the properties of this object by extracting them from a dictionary.

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        """
        self.errors = None
        if dictionary.get('Errors') is not None:
            self.errors = [Error7.from_dictionary(x) for x in dictionary.get('Errors')]
        else:
            self.errors = None
