# -*- coding: utf-8 -*-

"""
postnlecommerceapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CountryCode1Enum(object):

    """Implementation of the 'CountryCode1' enum.

    TODO: type enum description here.

    Attributes:
        NL: TODO: type description here.
        BE: TODO: type description here.

    """
    NL = 'NL'

    BE = 'BE'

