# -*- coding: utf-8 -*-

"""
postnlecommerceapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DeliveryOptions1Enum(object):

    """Implementation of the 'DeliveryOptions1' enum.

    TODO: type enum description here.

    Attributes:
        PG: TODO: type description here.
        PA: TODO: type description here.
        PG_EX: TODO: type description here.

    """
    PG = 'PG'

    PA = 'PA'

    PG_EX = 'PG_EX'

