# -*- coding: utf-8 -*-

"""
postnlecommerceapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Options1Enum(object):

    """Implementation of the 'Options1' enum.

    TODO: type enum description here.

    Attributes:
        DAYTIME: TODO: type description here.
        TODAY: TODO: type description here.
        SAMEDAY: TODO: type description here.
        EVENING: TODO: type description here.
        MORNING: TODO: type description here.
        NOON: TODO: type description here.
        SUNDAY: TODO: type description here.
        AFTERNOON: TODO: type description here.

    """
    DAYTIME = 'Daytime'

    TODAY = 'Today'

    SAMEDAY = 'Sameday'

    EVENING = 'Evening'

    MORNING = 'Morning'

    NOON = 'Noon'

    SUNDAY = 'Sunday'

    AFTERNOON = 'Afternoon'

