# -*- coding: utf-8 -*-

"""
postnlecommerceapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TypeEnum(object):

    """Implementation of the 'Type' enum.

    Specifies the type belonging to the cutoff time.

    Attributes:
        REGULAR: TODO: type description here.
        SAMEDAY: TODO: type description here.
        TODAY: TODO: type description here.

    """
    REGULAR = 'Regular'

    SAMEDAY = 'Sameday'

    TODAY = 'Today'

