# -*- coding: utf-8 -*-

"""
postnlecommerceapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Type1Enum(object):

    """Implementation of the 'Type1' enum.

    TODO: type enum description here.

    Attributes:
        ENUM_2S: TODO: type description here.
        ENUM_3S: TODO: type description here.
        CC: TODO: type description here.
        CP: TODO: type description here.
        CD: TODO: type description here.
        CF: TODO: type description here.
        LA: TODO: type description here.
        RI: TODO: type description here.
        UE: TODO: type description here.

    """
    ENUM_2S = '2S'

    ENUM_3S = '3S'

    CC = 'CC'

    CP = 'CP'

    CD = 'CD'

    CF = 'CF'

    LA = 'LA'

    RI = 'RI'

    UE = 'UE'

